// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvgxuxqnrevhjqqdizea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2Z3h1eHFucmV2aGpxcWRpemVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjE5NjEsImV4cCI6MjA2NDMzNzk2MX0.ff_3uVpsPWFmOeuZ0YgOmfd1VyE_R05lqZAIkSiV70s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);